

<!-- Javascript at the bottom for fast page loading -->

<!-- Grab Google CDN's jQuery. fall back to local if necessary -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>!window.jQuery && document.write('<script src="<?php echo $this->baseUrl('themes/'.$this->currentTheme.'/js/jquery-1.4.2.min.js'); ?>"><\/script>')</script>


<script src="<?php echo $this->baseUrl('themes/'.$this->currentTheme.'/js/plugins.js?v=1'); ?>"></script>
<script src="<?php echo $this->baseUrl('themes/'.$this->currentTheme.'/js/script.js?v=1'); ?>"></script>

<!--[if lt IE 7 ]>
  <script src="<?php echo $this->baseUrl('themes/.$this->currentTheme./js/dd_belatedpng.js?v=1'); ?>"></script>
<![endif]-->

<?php echo $this->googleAnalytics() ?>

