<?php echo $this->doctype('HTML5') . "\n" ?>
<html lang="de" class="no-js">
    <head>

        <?php echo $this->render('includes/header.phtml') ?>

    </head>

    <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->

    <!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
    <!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
    <!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
    <!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
    <!--[if gt IE 9]>  <body>             <![endif]-->
    <!--[if !IE]><!--> <body>         <!--<![endif]-->
        <div id="container">
            <?php echo $this->render('includes/top.phtml') ?>

            <div id="main">
                <?php echo $this->layout()->content ?>
            </div><!--! end of #main -->

            <?php echo $this->render('includes/sidebar.phtml'); ?>

            <?php echo $this->render('includes/footer.phtml'); ?>
            </div> <!--! end of #container -->

        <?php echo $this->render('includes/scripts.phtml'); ?>
    </body>
</html>
